<?php include app_path('views/layouts/header.php'); ?>
<div class="container-fluid"><div class="gh-card p-4 p-lg-5">
<div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4"><div><h2 class="mb-1"><?= $residentMode ? 'Pre-register Visitor' : 'Visitor Request' ?></h2><div class="text-muted"><?= $residentMode ? 'You are registering this visitor for House '.e($resident['house_number']).'.' : 'Enter the resident house and visitor details.' ?></div></div><a class="btn btn-outline-secondary rounded-pill" href="<?=e(url($residentMode?'resident/dashboard.php':'index.php'))?>">Back</a></div>
<form method="post" action="<?=e(url($residentMode?'resident/visitor.php':'visitor/register.php'))?>" enctype="multipart/form-data" class="row g-3"><?php if($residentMode): ?><?=csrf_field()?><?php endif; ?>
<?php if(!$residentMode): ?><div class="col-12"><label class="form-label">Resident House Number</label><div class="row g-2"><div class="col-md-4"><input class="form-control" id="visitorBlock" name="house_block" inputmode="numeric" placeholder="Block" required></div><div class="col-md-4"><input class="form-control" id="visitorLot" name="house_lot" inputmode="numeric" placeholder="Lot" required></div><div class="col-md-4"><input class="form-control text-uppercase" id="visitorLetter" name="house_letter" maxlength="1" placeholder="Letter (optional)"></div></div><input type="hidden" id="visitorHouseNumber" name="house_number"><div class="small text-muted mt-1">Stored as <strong id="visitorHousePreview">Block-Lot-Letter</strong> with no spaces.</div></div><?php endif; ?>
<div class="col-md-<?= $residentMode ? '6':'4' ?>"><label>Visitor Name</label><input class="form-control" name="visitor_name" required></div><div class="col-md-<?= $residentMode ? '6':'4' ?>"><label>Contact Number</label><input class="form-control" name="contact_number"></div>
<div class="col-12"><label>Vehicle(s)</label><div id="vehicleList"><div class="vehicle-row border rounded-4 p-3 mb-2"><div class="row g-2 align-items-end"><div class="col-md-4"><label>Plate Number</label><input class="form-control" name="vehicle_plate[]" required></div><div class="col-md-3"><label>Vehicle Type</label><select class="form-select" name="vehicle_type[]" required><option value="">Choose...</option><option value="car">Car</option><option value="motorcycle">Motorcycle</option><option value="truck">Truck</option><option value="other">Other</option></select></div><div class="col-md-3"><label>People in Vehicle</label><input class="form-control vehicle-people" type="number" name="vehicle_people[]" min="1" value="1" required></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger remove-vehicle w-100 d-none">Remove</button></div></div></div></div><button type="button" id="addVehicle" class="btn btn-outline-primary rounded-pill">+ Add another vehicle</button></div>
<div class="col-md-4"><label>Total People in Primary Vehicle</label><input class="form-control" id="peopleCount" name="people_count" type="number" min="1" value="1" required></div><div class="col-md-8"><label>Purpose</label><input class="form-control" name="purpose" required></div>
<div class="col-12"><label>Government ID</label><div class="gh-file"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="id_not_available" value="1" id="noId"><label class="form-check-label" for="noId">I cannot provide an ID</label></div><input class="form-control" type="file" name="government_id" id="governmentId" accept="image/*,.pdf"><div class="small mt-2">If no ID is available, check the box and continue.</div></div></div>
<div class="col-12"><button class="btn gh-gold rounded-pill py-3 px-4" type="submit">Generate Visitor Credentials</button></div></form></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const hb=document.getElementById('visitorBlock'),hl=document.getElementById('visitorLot'),hx=document.getElementById('visitorLetter'),hh=document.getElementById('visitorHouseNumber'),hp=document.getElementById('visitorHousePreview');function updateHouse(){if(!hb)return;const B=hb.value.trim(),L=hl.value.trim(),X=hx.value.trim().toUpperCase();hh.value=B&&L?B+'-'+L+(X?'-'+X:''):'';hp.textContent=hh.value||'Block-Lot-Letter';} [hb,hl,hx].filter(Boolean).forEach(el=>el.addEventListener('input',updateHouse));updateHouse();const list=document.getElementById('vehicleList'),add=document.getElementById('addVehicle'),noId=document.getElementById('noId'),file=document.getElementById('governmentId'),people=document.getElementById('peopleCount');add.addEventListener('click',()=>{const row=list.querySelector('.vehicle-row').cloneNode(true);row.querySelectorAll('input').forEach(i=>i.value=i.classList.contains('vehicle-people')?'1':'');row.querySelector('select').value='';row.querySelector('.remove-vehicle').classList.remove('d-none');list.appendChild(row);update();});list.addEventListener('click',e=>{if(e.target.classList.contains('remove-vehicle')){e.target.closest('.vehicle-row').remove();update();}});list.addEventListener('input',e=>{if(e.target.classList.contains('vehicle-people')&&e.target.closest('.vehicle-row')===list.querySelector('.vehicle-row'))people.value=e.target.value;});noId.addEventListener('change',()=>{file.disabled=noId.checked;if(noId.checked)file.value='';});function update(){const rows=list.querySelectorAll('.vehicle-row');rows.forEach((r,i)=>r.querySelector('.remove-vehicle').classList.toggle('d-none',i===0));}});</script>
<?php include app_path('views/layouts/footer.php'); ?>
/* BISM4RCK-KUN3H0 2026 */
