<?php
/* BISM4RCK-KUN3H0 2026 */ include app_path('views/layouts/header.php'); ?>
<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h2 class="mb-1">Admin Dashboard</h2><div class="text-muted">Manage the gate, accounts, vehicles, RFID, blacklist, logs, and staff tools.</div></div><span id="rfidListenerStatus" class="badge text-bg-success rounded-pill px-3 py-2"><i class="bi bi-broadcast me-1"></i>RFID LISTENING</span></div>
  <section class="gh-card p-4 mb-4 admin-override-card"><div class="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><h4 class="mb-1"><i class="bi bi-unlock me-2"></i>Gate Control</h4><div class="text-muted">Open the gate manually for an authorized vehicle or emergency.</div></div><span class="badge text-bg-danger rounded-pill px-3 py-2">ADMIN OVERRIDE</span></div><form method="post" class="row g-2 align-items-end mt-2"><?=csrf_field()?><input type="hidden" name="action" value="gate_override"><div class="col-md-4"><label class="form-label">Plate Number</label><input class="form-control form-control-lg" name="plate_number" placeholder="ABC 1234"></div><div class="col-md-2"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="emergency" id="adminEmergency" value="1"><label class="form-check-label fw-semibold" for="adminEmergency">EMERGENCY</label></div></div><div class="col-md-4"><label class="form-label">Reason</label><input class="form-control form-control-lg" name="reason" placeholder="Reason / incident"></div><div class="col-md-2"><button class="btn btn-danger btn-lg w-100" type="submit">Open Gate</button></div></form></section>
  <div class="row g-3 mb-4"><div class="col-lg-6"><div class="gh-card p-4 h-100"><h5><i class="bi bi-person-badge me-2"></i>Visitor ID</h5><div class="text-muted mb-3">Enter a visitor's 6-character credential to check the current request status.</div><form method="post" class="d-flex gap-2"><?=csrf_field()?><input type="hidden" name="action" value="visitor_id_check"><input class="form-control form-control-lg text-uppercase" name="visitor_id" maxlength="6" pattern="[A-Za-z0-9]{6}" placeholder="ABC123" required><button class="btn gh-primary btn-lg px-4">Check</button></form></div></div><div class="col-lg-6"><div class="gh-card p-4 h-100"><h5><i class="bi bi-broadcast me-2"></i>RFID Access</h5><div class="text-muted">The ESP32 + RC522 reader is continuously listening. Present an RFID card at the reader; no UID entry is required.</div></div></div></div>
  <div class="gh-action-grid mb-4"><a class="btn gh-primary gh-action-square" href="<?=e(url('admin/vehicles.php'))?>"><i class="bi bi-car-front"></i>Vehicles</a><a class="btn gh-gold gh-action-square" href="<?=e(url('admin/users.php'))?>"><i class="bi bi-people"></i>Users</a><a class="btn gh-btn-soft gh-action-square" href="<?=e(url('admin/rfid.php'))?>"><i class="bi bi-credit-card-2-front"></i>RFID</a><a class="btn btn-outline-danger gh-action-square" href="<?=e(url('admin/blacklist.php'))?>"><i class="bi bi-slash-circle"></i>Blacklist</a><a class="btn gh-btn-soft gh-action-square" href="<?=e(url('admin/logs.php'))?>"><i class="bi bi-journal-text"></i>Gate Logs</a><a class="btn gh-btn-soft gh-action-square" href="<?=e(url('admin/activity-logs.php'))?>"><i class="bi bi-person-lines-fill"></i>Admin / Guard Logs</a><a class="btn gh-btn-soft gh-action-square" href="<?=e(url('admin/settings.php'))?>"><i class="bi bi-sliders"></i>Customize</a><a class="btn gh-gold gh-action-square" href="<?=e(url('admin/walkin.php'))?>"><i class="bi bi-person-plus"></i>Walk-in Visitor</a><a class="btn gh-btn-soft gh-action-square" href="<?=e(url('admin/tickets.php'))?>"><i class="bi bi-chat-left-text"></i>Tickets</a></div>
  <div class="row g-2 gh-small-stats mb-4"><div class="col-6 col-md-3"><div class="gh-stat"><div class="label">Residents</div><div class="value"><?= (int)$stats['residents'] ?></div></div></div><div class="col-6 col-md-3"><div class="gh-stat"><div class="label">Requests</div><div class="value"><?= (int)$stats['requests'] ?></div></div></div><div class="col-6 col-md-3"><div class="gh-stat"><div class="label">Tickets</div><div class="value"><?= (int)$stats['tickets'] ?></div></div></div><div class="col-6 col-md-3"><div class="gh-stat"><div class="label">Gate Logs</div><div class="value"><?= (int)$stats['logs'] ?></div></div></div></div>
  <div class="row g-3"><div class="col-lg-7"><div class="gh-card p-4"><div class="d-flex justify-content-between"><h5>Open Tickets</h5><a href="<?=e(url('admin/tickets.php'))?>">Open all</a></div><div class="d-grid gap-3 mt-3"><?php foreach($tickets as $t): ?><div class="gh-card-soft p-3"><div class="fw-semibold"><?=e($t['subject']??'Ticket')?></div><div class="small text-muted"><?=e($t['status']??'open')?></div></div><?php endforeach;?></div></div></div><div class="col-lg-5"><div class="gh-card p-4"><h5>Recent Gate Activity</h5><div class="d-grid gap-2 mt-3"><?php foreach($logs as $log): ?><div class="d-flex justify-content-between gap-3"><span><?=e($log['event_type'])?></span><span class="badge <?=e(gate_badge($log['gate_status']))?>"><?=e($log['gate_status'])?></span></div><?php endforeach;?></div></div></div></div>
</div>
<div class="modal fade" id="gateResultModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow-lg"><div class="modal-header border-0 pb-0"><div id="gateResultLocation" class="small fw-bold text-uppercase text-muted"></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body text-center p-5 pt-3"><div id="gateResultIcon" class="display-3 mb-3"></div><h2 id="gateResultTitle" class="fw-bold"></h2><p id="gateResultText" class="text-muted mb-0"></p></div></div></div></div>
<script>
(()=>{
let afterId=<?= (int)$latestGateLogId ?>;
const modalEl=document.getElementById('gateResultModal');
const modal=window.bootstrap&&modalEl?new bootstrap.Modal(modalEl):null;
const title=document.getElementById('gateResultTitle'),text=document.getElementById('gateResultText'),icon=document.getElementById('gateResultIcon'),location=document.getElementById('gateResultLocation'),listener=document.getElementById('rfidListenerStatus');
let fallbackTimer=null;
function popup(kind,heading,message){
 title.textContent=heading;text.textContent=message||'';
 icon.innerHTML=kind==='success'?'<i class=\"bi bi-check-circle-fill text-success\"></i>':kind==='warning'?'<i class=\"bi bi-hourglass-split text-warning\"></i>':'<i class=\"bi bi-x-circle-fill text-danger\"></i>';
 if(modal){modal.show();return;}
 modalEl.classList.add('show');modalEl.style.display='block';modalEl.removeAttribute('aria-hidden');modalEl.setAttribute('aria-modal','true');
 clearTimeout(fallbackTimer);fallbackTimer=setTimeout(()=>{modalEl.classList.remove('show');modalEl.style.display='none';modalEl.setAttribute('aria-hidden','true');},4500);
}
function showEvent(event){const status=String(event.gate_status||'').toLowerCase();const gate=String(event.reader||'').toLowerCase()==='exit'?'EXIT GATE':'ENTRY GATE';location.textContent=gate;popup(status==='approved'?'success':status==='pending'?'warning':'danger',status==='approved'?'GATE OPENED':status==='pending'?'REQUEST STILL PENDING':'DENIED',event.log_notes||'RFID access result received.');}
async function poll(){try{const r=await fetch('<?=e(url('api/live_rfid.php'))?>?after_id='+encodeURIComponent(afterId),{cache:'no-store',credentials:'same-origin',headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(d.ok&&Array.isArray(d.events)&&d.events.length){d.events.forEach(showEvent);afterId=Number(d.events[d.events.length-1].id);}listener.className='badge text-bg-success rounded-pill px-3 py-2';listener.innerHTML='<i class=\"bi bi-broadcast me-1\"></i>RFID LISTENING';}catch(e){listener.className='badge text-bg-secondary rounded-pill px-3 py-2';listener.innerHTML='<i class=\"bi bi-broadcast-pin me-1\"></i>RFID RECONNECTING';}}
setInterval(poll,250);poll();
const cmdId=<?= (int)$gateCommandId ?>;
if(cmdId){const check=async()=>{try{const r=await fetch('<?=e(url('api/gate_command_status.php'))?>?command_id='+cmdId,{cache:'no-store',credentials:'same-origin'}),d=await r.json();if(d.ok&&d.status==='completed'){location.textContent='GATE CONTROL';popup('success','GATE OPENED','The ESP32 confirmed the gate command.');return;}if(d.ok&&d.status==='expired'){location.textContent='GATE CONTROL';popup('danger','ERROR!','The gate command expired before the gate opened.');return;}setTimeout(check,750);}catch(e){setTimeout(check,1000);}};check();}
})();
</script>
<?php include app_path('views/layouts/footer.php'); ?>