<?php
/* BISM4RCK/KUN3H0 2026 */
include app_path('views/layouts/header.php');
?>
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="display-6 fw-semibold mb-0">Account Management</h1><div class="text-muted">Create accounts with role-specific requirements.</div></div><a class="btn btn-outline-secondary rounded-pill" href="<?=e(url('admin/dashboard.php'))?>">Dashboard</a></div>
<div class="row g-3"><div class="col-xl-5"><div class="gh-card p-4"><h3 class="h5">Add account</h3><form method="post" id="accountForm" class="d-grid gap-3"><?=csrf_field()?><input type="hidden" name="action" value="create_user"><div><label>Account type *</label><select class="form-select form-select-lg" id="accountRole" name="role" required><option value="">Select type</option><option value="resident">Resident</option><option value="guard">Guard</option><option value="admin">Admin</option></select></div><input class="form-control" name="full_name" placeholder="Full name" required><input class="form-control" type="email" name="email" placeholder="Email" required><input class="form-control" type="password" name="password" placeholder="Password" minlength="6" required>
<div id="residentFields" class="role-fields d-grid gap-2"><input class="form-control" name="block_number" placeholder="Block number"><input class="form-control" name="lot_number" placeholder="Lot number"><input class="form-control" name="household_suffix" placeholder="Household letter (A, B, C...)"><div class="form-text">Address is generated as Block - Lot or Block - Lot - Letter.</div></div>
<div id="guardFields" class="role-fields d-grid gap-2"><input class="form-control" name="guard_code" placeholder="Guard ID"><input class="form-control" name="shift_name" placeholder="Shift"><input class="form-control" name="contact_number" placeholder="Contact number"></div>
<div id="adminFields" class="role-fields"><input class="form-control" name="admin_code" placeholder="Admin ID"></div>
<button class="btn gh-primary btn-lg">Create account</button></form></div></div>
<div class="col-xl-7"><div class="gh-card p-4 mb-3"><h3 class="h5">Residents</h3><div class="table-responsive"><table class="table gh-table"><thead><tr><th>Name</th><th>House</th><th>Email</th><th></th></tr></thead><tbody><?php foreach($residents as $r): ?><tr><td><?=e($r['full_name'])?></td><td><?=e($r['house_number'])?></td><td><?=e($r['email'])?></td><td><form method="post" onsubmit="return confirm('Remove resident?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?= (int)$r['user_id']?>"><button class="btn btn-sm btn-outline-danger">Remove</button></form></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="gh-card p-4"><h3 class="h5">Guards & Admins</h3><div class="table-responsive"><table class="table gh-table"><thead><tr><th>Name</th><th>Role</th><th>ID</th><th></th></tr></thead><tbody><?php foreach(array_merge($guards,$admins) as $u): ?><tr><td><?=e($u['full_name'])?></td><td class="text-capitalize"><?=e($u['role'])?></td><td><?=e($u['email'])?></td><td><?php if((int)$u['id']!==(int)current_user()['id']): ?><form method="post" onsubmit="return confirm('Remove account?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?= (int)$u['id']?>"><button class="btn btn-sm btn-outline-danger">Remove</button></form><?php else:?><span class="badge text-bg-light">Current admin</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="gh-card p-4 mt-3"><h3 class="h5">Vehicle / Visitor Blacklist</h3>
<form method="post" class="row g-2 align-items-end mb-3"><?=csrf_field()?><input type="hidden" name="action" value="blacklist_add"><div class="col-md-3"><label>Plate</label><input class="form-control" name="plate_number"></div><div class="col-md-3"><label>Visitor name</label><input class="form-control" name="visitor_name"></div><div class="col-md-4"><label>Reason *</label><input class="form-control" name="reason" required></div><div class="col-md-2"><button class="btn btn-danger w-100">Blacklist</button></div></form>
<?php foreach($blacklist as $b): ?><div class="border rounded-3 p-3 mb-2 d-flex justify-content-between align-items-center"><div><strong><?=e($b['plate_number'] ?: mb_convert_case($b['visitor_name'],MB_CASE_TITLE,'UTF-8'))?></strong><div class="small text-muted"><?=e($b['reason'])?> · Added by <?=e($b['created_by_name'] ?? 'Unknown')?></div></div><form method="post" onsubmit="return confirm('Remove blacklist entry?')"><?=csrf_field()?><input type="hidden" name="action" value="blacklist_remove"><input type="hidden" name="blacklist_id" value="<?= (int)$b['id']?>"><button class="btn btn-sm btn-outline-danger">Remove</button></form></div><?php endforeach; ?>
</div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const r=document.getElementById('accountRole'), boxes={resident:document.getElementById('residentFields'),guard:document.getElementById('guardFields'),admin:document.getElementById('adminFields')};function sync(){Object.entries(boxes).forEach(([k,b])=>{const on=r.value===k;b.style.display=on?'grid':'none';b.querySelectorAll('input').forEach(i=>i.required=on);});}r.addEventListener('change',sync);sync();});
</script>
<?php include app_path('views/layouts/footer.php'); ?>
