<?php
/* BISM4RCK/KUN3H0 2026 */
include app_path('views/layouts/header.php');
?>
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="display-6 fw-semibold mb-0">Vehicle Management</h1><div class="text-muted">Filter resident vehicles by house number or view all.</div></div><a class="btn btn-outline-secondary rounded-pill" href="<?=e(url('admin/dashboard.php'))?>">Dashboard</a></div>
<div class="gh-card p-4 mb-3"><form method="get" class="row g-2 align-items-end"><div class="col-md-7"><label>Resident house number</label><input class="form-control" name="house" value="<?=e($house)?>" placeholder="e.g. 12-A"></div><div class="col-md-2"><button class="btn gh-primary w-100">Filter</button></div><div class="col-md-2"><a class="btn btn-outline-secondary w-100" href="<?=e(url('admin/vehicles.php'))?>">View All</a></div></form></div>
<div class="gh-card p-4 mb-3"><h3 class="h5">Add vehicle</h3><form method="post" class="row g-2 align-items-end"><?=csrf_field()?><input type="hidden" name="action" value="add"><input type="hidden" name="house_filter" value="<?=e($house)?>"><div class="col-md-3"><label>Owner type *</label><select class="form-select" id="ownerRole" name="owner_role" required><option value="">Select</option><option value="resident">Resident</option><option value="guard">Guard</option><option value="admin">Admin</option></select></div><div class="col-md-4"><label>Owner *</label><select class="form-select" id="ownerUser" name="owner_user_id" required><option value="">Select type first</option></select></div><div class="col-md-2"><label>Plate *</label><input class="form-control" name="plate_number" required></div><div class="col-md-2"><label>Type *</label><select class="form-select" name="vehicle_type" required><option>Car</option><option>Motorcycle</option><option>Truck</option><option>Other</option></select></div><div class="col-md-1"><label>Color</label><input class="form-control" name="color"></div><div class="col-12"><button class="btn gh-primary">Add vehicle</button></div></form></div>
<div class="gh-card p-4"><div class="table-responsive"><table class="table gh-table align-middle"><thead><tr><th>Plate</th><th>Owner</th><th>House</th><th>Role</th><th>Type</th><th></th></tr></thead><tbody><?php foreach($vehicles as $v): ?><tr><td class="fw-semibold"><?=e($v['plate_number'])?></td><td><?=e($v['full_name'])?></td><td><?=e($v['house_number'] ?? '—')?></td><td class="text-capitalize"><?=e($v['owner_role'])?></td><td><?=e(ucfirst($v['vehicle_type']))?></td><td><form method="post" onsubmit="return confirm('Remove vehicle?')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="vehicle_id" value="<?= (int)$v['id']?>"><input type="hidden" name="house_filter" value="<?=e($house)?>"><button class="btn btn-sm btn-outline-danger">Remove</button></form></td></tr><?php endforeach;?><?php if(!$vehicles): ?><tr><td colspan="6" class="text-center text-muted py-4">No vehicles found.</td></tr><?php endif;?></tbody></table></div></div></div>
<script>
const owners={resident:<?=json_encode(array_map(fn($x)=>['id'=>$x['user_id'],'name'=>$x['full_name'].' — '.$x['house_number']],$residents))?>,guard:<?=json_encode(array_map(fn($x)=>['id'=>$x['id'],'name'=>$x['full_name']],$guards))?>,admin:<?=json_encode(array_map(fn($x)=>['id'=>$x['id'],'name'=>$x['full_name']],$admins))?>};
document.getElementById('ownerRole').addEventListener('change',e=>{const s=document.getElementById('ownerUser');s.innerHTML='<option value="">Select owner</option>';(owners[e.target.value]||[]).forEach(o=>s.insertAdjacentHTML('beforeend',`<option value="${o.id}">${o.name}</option>`));});
</script>
<?php include app_path('views/layouts/footer.php'); ?>
